name: pubish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Print inputs
      run: |
        echo 'sha: ${{ github.sha }}'
        echo 'ref  : ${{ github.ref }}'
