name: pubish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Debug information
      run: |
        echo 'sha: ${{ github.sha }}'
        echo 'ref: ${{ github.ref }}'

    # This action will download the artifact for workflow runs that
    # happen for this actual commit (the commit that the tag points to).
    # It also restores the files timestamps.
    - name: Download artifacts from commit ${{ github.sha }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: wheels.yaml
        workflow_conclusion: success
        commit: ${{ github.sha }}
        name: wheels
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v2.2.2

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
