name: wheels

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Generate sdist and wheel
      run: python -m build -s -w .

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  release:
    needs:
    - wheel
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
    - run: |
        echo ${{ github.event_name }}
